name: example
version: 0.1.0
homepage: https://apirious.com
author: Colin Daum <colin.daum@apirious.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  viewmodel:
  provider: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  viewmodel:
    path: ../

flutter:
  uses-material-design: true
