name: example
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  viewmodel:
  provider: ^6.0.5
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  viewmodel:
    path: ../

flutter:
  uses-material-design: true
