name: viewmodel
description: A Flutter package providing ViewModel support.
version: 0.1.3+2
author: Colin Daum <colin.daum@hotmail.de>
homepage: https://apirious.com/

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ">=4.0.0 <5.0.0"
  quiver: ">=1.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: