name: viewmodel
description: A Flutter package providing ViewModel support.
version: 0.2.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ">=5.0.0 <7.0.0"
  quiver: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: